- file:
    path: /home/dbelros1
    state: directory
    mode: 0700
    owner: dbelros1

- authorized_key: user=dbelros1 key="{{ item }}"
  become: true
  become_user: root
  become_method: sudo
  with_file:
    - public_keys/derek_secure.pub

- authorized_key: user=dbelros1 key="{{ item }}" state=absent
  with_file:
    - public_keys/derek_mbp13.pub
    - public_keys/derek_home.pub
    - public_keys/jgara1.pub

- copy: 
    src: "/etc/skel/{{ item }}"
    dest: /home/dbelros1/{{item}}
    owner: dbelros1
    group: msel-wheel
    force: no
    remote_src: true
  with_items:
    - ".bash_logout"
    - ".bash_profile"
    - ".bashrc"
