---
- name: Playbook for psql03.mse.jhu.edu Operations
  hosts: psql03.mse.jhu.edu
  vars_prompt:
    - name: "domain_username"
      prompt: "Enter domain username"
      private: no

    - name: "domain_password"
      prompt: "Enter domain password"
      private: yes

  tasks:
    - include: ops.yml
    - include: pbis.yml username=domain_username domain_passowrd=domain_password
    - include: staff_keys.yml
    - include: sudoers.yml
