---
- name: Playbook for Library Operations
  hosts: all

  roles:
    - common

- name: Web Certificates
  hosts: linux-webservers

  roles:
    - webserver

- name: Docker playbook
  hosts: infrastructure-docker
  roles:
    - docker


- name: Nagios Servers
  hosts: nagios-servers
  roles:
    - nagios-server
