---
- name: Playbook for Library Operations
  hosts: all
  vars_prompt:
    - name: "domain_username"
      prompt: "Enter domain username"
      private: no

    - name: "domain_password"
      prompt: "Enter domain password"
      private: yes

  roles:
    - common

