---
- name: restart ntpd
  become: true
  service: name=ntpd state=restarted

- name: restart sshd
  become: true
  service: name=sshd state=restarted

- name: restart nrpe
  become: true
  service: name=nrpe state=restarted

- name: restart firewalld
  become: true
  service: name=firewalld state=restarted

- name: systemd fail2ban daemon-reload
  systemd: daemon_reload=yes name=fail2ban 

- name: restart postfix
  service: name=postfix state=restarted
  
