---
- include: epel.yml
- include: pbis.yml username={{ domain_username }} password={{ domain_password }}
- include: ops.yml
- include: staff_keys.yml 
- include: sudoers.yml
- include: nagios-nrpe.yml
- include: spacewalk.yml

- name: Open up SSHd in firewalld
  become: true
  firewalld: service=ssh permanent=true state=enabled

- name: Ensure ntp is installed
  become: true
  yum: name=ntp state=installed
  tags: ntp

- name: Ensure ntp is configured
  become: true
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: Ensure ntpd is running and enabled
  become: true
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: Install vim
  become: true
  yum: name=vim state=installed

- name: Ensure sysstat is installed
  become: true
  yum: name=sysstat state=installed

- name: Ensure yum-utils is installed
  become: true
  yum:
    name: yum-utils
    state: latest

- name: Ensure fail2ban is installed
  become: true
  yum:
    name: fail2ban
    state: latest

- name: Copy altered (fixed) fail2ban.service into /etc/systemd/system
  copy:
    src: fail2ban.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 644
  notify: systemd fail2ban daemon-reload 

- name: Ensure fail2ban is enabled and started
  become: true
  service: name=fail2ban state=started enabled=yes

- name: Uninstall microcode
  package:
    name: microcode_ctl
    state: absent
  when: ansible_virtualization_role == "guest"

- name: Install tmux
  yum: name=tmux state=installed

- name: Install open-vm-tools on CentOS/RHEL 7 VMs
  yum:
    name: open-vm-tools
    state: latest
  when: (ansible_virtualization_role == "guest") and
        (ansible_os_family == "RedHat") and
        (ansible_distribution_major_version == "7")

