---
- name: Ensure nrpe is installed
  become: true
  yum: name=nrpe state=installed

- name: Ensure nagios-plugins-all is installed
  become: true
  yum: name=nagios-plugins-all state=installed

- name: Ensure nrpe.cfg is what we want it to be
  become: true
  notify:
    - restart nrpe
  template:
    src=nrpe.cfg.j2
    dest=/etc/nagios/nrpe.cfg
    owner=root
    group=root
    mode=0644
    backup=yes

- name: Ensure NRPE port (5666) is open in firewalld
  become: true
  firewalld: port=5666/tcp state=enabled permanent=true
  notify:
    - restart firewalld

- name: Ensure nrpe service is installed, enabled and running
  become: true
  service: name=nrpe state=started enabled=yes

- name: Ensure NRPE check check_root_drive is installed and configured
  become: true
  lineinfile: 
   dest=/etc/nrpe.d/check_root.cfg
   line='command[check_root]=/usr/lib64/nagios/plugins/check_disk -w 10% -c 5% -p /'
   state=present
   create=yes
   mode=0644
  notify:
   - restart nrpe

- name: Ensure NRPE check check_cpu_perf is configured
  become: true
  lineinfile:
    dest=/etc/nrpe.d/check_cpu_perf.cfg
    line='command[check_cpu_perf]=/usr/lib64/nagios/plugins/check_cpu_perf.sh 10 5'
    state=present
    create=yes
    mode=0644
  notify:
    - restart nrpe

- name: Ensure check_cpu_perf.sh is in the nagios plugins directory
  become: true
  copy:
    src: check_cpu_perf.sh
    dest: /usr/lib64/nagios/plugins/check_cpu_perf.sh
    owner: root
    group: root
    mode: 0755
