- authorized_key: user=ops key="{{ item }}"
  with_file:
    - public_keys/derek_secure.pub

- authorized_key: user=ops key="{{item}}" state=absent
  with_file:
    - public_keys/derek_mbp13.pub
    - public_keys/derek_home.pub
    
- name: Creates sudoers file for ops user
  become: true
  become_user: root
  become_method: sudo
  lineinfile:
    dest=/etc/sudoers.d/ops
    line="ops  ALL=(ALL) NOPASSWD{{':'}} ALL"
    state=present
    create=yes
    validate='/sbin/visudo -cf %s'
