- include: sudoers/operations.yml

- name: Setup up other sudoer files
  become: true
  lineinfile:
   dest=/etc/sudoers.d/msel-{{item}}
   line='%msel-{{item}} ALL=(ALL) ALL'
   state=present
   create=yes
   validate='visudo -cf %s'
  with_items:
    "{{ sudoers|default([]) }}"

- name: copy a default sudoers file to /etc/sudoers
  become: true
  copy: src=files/sudoers dest=/etc/sudoers owner=root group=root mode=0440
