- include: sudoers/operations.yml

- name: Setup up other sudoer files
  become: true
  lineinfile:
   dest=/etc/sudoers.d/msel-{{item}}
   line='%msel-{{item}} ALL=(ALL) ALL'
   state=present
   create=yes
   validate='visudo -cf %s'
  with_items:
    "{{ sudoers|default([]) }}"
