---
- name: Install Apache HTTPd
  package: name=httpd state=latest

- name: Install mod_ssl
  package: name=mod_ssl state=latest

- name: Set apache httpd to start on boot and start service
  service: name=httpd state=running enabled=yes

- name: Load SSL files
  include_vars: main.yml
  no_log: true

- name: Populate SSL Certificates
  become: true
  copy: content={{ssl_certs[item].cert}} dest=/etc/pki/tls/certs/{{ item }}.crt owner=root group=root mode=0644
  with_list:
    "{{ ssl_certificates|default({}) }}"
  when:
    ssl_certificates is defined

- name: Populate SSL Interim Certificates
  become: true
  copy: content={{ssl_certs[item].interim}} dest=/etc/pki/tls/certs/{{ item }}_interim.crt owner=root group=root mode=0644
  with_list:
    "{{ ssl_certificates|default({}) }}"
  when:
    ssl_certificates is defined

- name: Populate SSL Keys
  become: true
  copy: content={{ssl_certs[item].key}} dest=/etc/pki/tls/private/{{item}}.key owner=root group=root mode=0600
  with_list:
    "{{ ssl_certificates|default({}) }}"
  when:
    ssl_certificates is defined

 
- name: Open up HTTP in firewalld
  firewalld: service=http permanent=true state=enabled

- name: Open up HTTPS in firewalld
  firewalld: service=https permanent=true state=enabled
